# Generated by Django 4.2.4 on 2023-10-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='custom_url',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='paypal_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
