# Generated by Django 4.2.4 on 2023-10-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_tag',
            name='score',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='userinterests',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
