# Generated by Django 4.2.4 on 2023-10-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_tag_score_alter_userinterests_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='post_tag',
            name='score',
            field=models.TextField(default='0'),
        ),
    ]
