# Generated by Django 4.2.4 on 2023-10-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_link_alter_post_tag_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_tag',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
